
# Build on each commit

name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board_config: [
          ../boards/esp32-cube/configs/nsh,
          ../boards/esp32s3-tiny/configs/nsh
        ]
    steps:
      - name: Checkout NuttX
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-nuttx
          path: nuttx

      - name: Checkout NuttX Apps
        uses: actions/checkout@v4
        with:
          repository: apache/incubator-nuttx-apps
          path: apps

      - name: Checkout Boards
        uses: actions/checkout@v4
        with:
          path: boards

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential kconfig-frontends-nox genromfs
          sudo apt-get install -y python3 python3-pip

          pip3 install esptool

          mkdir -p tools
          curl -L https://github.com/espressif/crosstool-NG/releases/download/esp-13.2.0_20230928/xtensa-esp-elf-13.2.0_20230928-x86_64-linux-gnu.tar.xz | tar -xJ -C tools
          echo "$PWD/tools/xtensa-esp-elf/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          cd nuttx
          tools/configure.sh ${{ matrix.board_config }}
          make -j$(nproc)
