
# Build on each commit and daily

on:
  push:
  schedule:
    - cron:  '0 0 * * *'

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        board_config: [
          ../boards/esp32-cube/configs/nsh,
          ../boards/esp32s3-tiny/configs/nsh
        ]
    steps:
      - name: Checkout NuttX
        uses: actions/checkout@v3
        with:
          repository: apache/incubator-nuttx
          path: nuttx

      - name: Checkout NuttX Apps
        uses: actions/checkout@v3
        with:
          repository: apache/incubator-nuttx-apps
          path: apps

      - name: Checkout Boards
        uses: actions/checkout@v3
        with:
          path: boards

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential kconfig-frontends-nox genromfs
          sudo apt-get install -y python3 python3-pip

          pip3 install esptool

          mkdir -p tools
          curl -L https://github.com/espressif/crosstool-NG/releases/download/esp-12.2.0_20230208/xtensa-esp32-elf-12.2.0_20230208-x86_64-linux-gnu.tar.xz | tar -xJ -C tools
          curl -L https://github.com/espressif/crosstool-NG/releases/download/esp-12.2.0_20230208/xtensa-esp32s3-elf-12.2.0_20230208-x86_64-linux-gnu.tar.xz | tar -xJ -C tools
          echo "$PWD/tools/xtensa-esp32-elf/bin" >> $GITHUB_PATH
          echo "$PWD/tools/xtensa-esp32s3-elf/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          cd nuttx
          tools/configure.sh ${{ matrix.board_config }}
          make -j$(nproc)
